services:
  app:
    image: node:alpine
    container_name: Node_Backend
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - app-network
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: Redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: Redis-Commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: